apiVersion: apps/v1
kind: Deployment
metadata:
  name: dm-arthas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arthas
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: arthas
    spec:
      containers:
        - name: arthas
          image: registry.cn-hongkong.aliyuncs.com/hocgin/arthas:latest
          imagePullPolicy: Always
          args: [ "--spring.profiles.active=${ACTIVE}" ]
          ports:
            - name: web
              containerPort: 8080
            - name: ws
              containerPort: 7777
          envFrom:
            - configMapRef:
                name: cm-service-env
          livenessProbe:
            httpGet:
              path: "/actuator/health"
              port: 8080
            initialDelaySeconds: 160
            periodSeconds: 10
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 5
---
apiVersion: v1
kind: Service
metadata:
  name: sv-arthas
spec:
  type: NodePort
  ports:
    - name: web
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: arthas
