# arthas tunnel server host
arthas:
  server:
    host: 0.0.0.0
    port: 7777
  enable-detail-pages: true

spring:
  application:
    name: arthas
  profiles:
    active: local
  cache:
    type: caffeine
    cache-names: inMemoryClusterCache
    caffeine:
      spec: maximumSize=3000,expireAfterAccess=3600s
server:
  port: 8080

# for all endpoints
management:
  endpoints:
    web:
      exposure:
        include: '*'

#arthas.embedded-redis.enabled=true
#arthas.embedded-redis.settings=maxmemory 128M
#spring.redis.host=127.0.0.1

